version: '3.7'

services:

  composer:
    build:
      context: .
      dockerfile: Dockerfile-composer
    volumes:
      - ./src:/var/www/html
    command: composer install --ignore-plataform-reqs

  app:
    image: app
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
    #  - db

  # db:
  #   container_name: mysql
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: Makeup
